set nocompatible
set number
set wrap
set linebreak
set mouse=
syntax on
set showcmd
set ruler
set showmatch
set showtabline=2
set laststatus=2
set title
set visualbell
set hidden
set t_Co=256
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set list
set cursorline
set pastetoggle=
set autoread
set keymap=russian-jcukenwin
set iminsert=0
set splitright
set foldmethod=syntax
set completeopt=longest,menuone
set hlsearch
set incsearch
set smartcase
set nowrapscan
set ignorecase
set imsearch=0
